# Generated by Django 2.2.6 on 2019-11-14 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
